### ISSUE TITLE
Mehrere Wechselrichter

### ISSUE THREAD

**Issue by Ackmachine** [niltrip/powerocean#13]
## System Information

version | core-2024.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4988
Installed Version | 2.0.1
Stage | running
Available Repositories | 1469
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 5.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | oracle
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Get HACS (1.3.1), File editor (5.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 1
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 27. November 2024 um 15:52
-- | --
current_recorder_run | 28. November 2024 um 11:36
estimated_db_size | 4.31 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Moin, ich habe neurdings auch eine PV Anlage von Ecoflow auf dem Dach, aber mit zwei Wechselrichtern. ein 12kW WR, der auch die Batterie versorgt und ein 10kw, der nur das Haus versorgt und einspeist. 
Den 12kW  kann ich auch integrieren und es läuft soweit ganz gut. Beim 10kW bekomme ich aber nach der Anmeldung, keine Entitäten angezeigt und kann damit eine Dachseite nicht auswerten, was die Statistik ja leider quasi unbrauchbar macht. 

Diese Fehlermeldung taucht in den Protokollen auf:

Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:365
Integration: Sensor ([Dokumentation](https://www.home-assistant.io/integrations/sensor), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
Erstmals aufgetreten: 11:48:58 (1 Vorkommnisse)
Zuletzt protokolliert: 11:48:58
Error while setting up powerocean platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/powerocean/sensor.py", line 54, in async_setup_entry
    data = await hass.async_add_executor_job(ecoflow.fetch_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/powerocean/ecoflow.py", line 120, in fetch_data
    response = self.get_json_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/powerocean/ecoflow.py", line 106, in get_json_response
    raise Exception(f"{response_message}")
Exception: 非法设备

Hat da jemand eine Idee?

### Reproduction steps

1.
2.
3.
...
.

### Debug logs

```text
Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:365
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 11:48:58 (1 Vorkommnisse)
Zuletzt protokolliert: 11:48:58
Error while setting up powerocean platform for sensor

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/powerocean/sensor.py", line 54, in async_setup_entry
data = await hass.async_add_executor_job(ecoflow.fetch_data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/powerocean/ecoflow.py", line 120, in fetch_data
response = self.get_json_response(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/powerocean/ecoflow.py", line 106, in get_json_response
raise Exception(f"{response_message}")
Exception: 非法设备
```

**Comment by AndyBowden** [comment]
Is this Power Ocean a dual master / slave inverter configuration or 2 independent inverters?
If the former, discussion #10 is relevant

**Comment by Ackmachine** [comment]
Ah thanks. I believe it is master/slave. I try to contribute my own log in that discussion over the next few days when I have some free time. Maybe it will help for the development.

**Comment by lilalinux** [comment]
非法设备 ist Chinesisch und bedeutet:

🚫 "Illegales Gerät" oder "Ungültiges Gerät"

**Comment by lilalinux** [comment]
I have the same problem in a master/slave setup, when adding the 2nd Inverter (slave). Master shows 67 entities, slave shows only the device, but no entities and logs the error. I tried several times and the SN is correct.

Both Hybrid-Inverters are 12kw.

Home Assistant Core: 2025.4.0
Integration: 2025.01.07


2025-04-04 12:41:53.764 INFO (SyncWorker_1) [custom_components.powerocean] Login to EcoFlow API {'https://api.ecoflow.com/auth/login'}
2025-04-04 12:41:53.864 INFO (SyncWorker_1) [custom_components.powerocean] Successfully logged in: {'EcoFlow User'}
2025-04-04 12:42:13.130 INFO (SyncWorker_3) [custom_components.powerocean] Login to EcoFlow API {'https://api.ecoflow.com/auth/login'}
2025-04-04 12:42:13.232 INFO (SyncWorker_3) [custom_components.powerocean] Successfully logged in: {'EcoFlow User'}
2025-04-04 12:42:13.291 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up powerocean platform for sensor: 非法设备
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/powerocean/sensor.py", line 54, in async_setup_entry
    data = await hass.async_add_executor_job(ecoflow.fetch_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/powerocean/ecoflow.py", line 123, in fetch_data
    response = self.get_json_response(request)
  File "/config/custom_components/powerocean/ecoflow.py", line 106, in get_json_response
    raise Exception(f"{response_message}")
Exception: 非法设备

**Comment by lilalinux** [comment]
I tried fetching the data manually via curl, but only the master SN returns data, everything else (slave, battery1, battery2) return code 8705 非法设备 (Illegal Device)

**Comment by lilalinux** [comment]
I think this issue can be closed and another issue needs to be opened for master/slave.
For master/slave you must not add multiple integrations, but all the data is already included in the master json's JTS1_PARALLEL_ENERGY_STREAM_REPORT
